#!/usr/bin/env python3
"""
Monitor and clean bad candles (with wicks) from database
Run this continuously to remove bad candles generated by old deployments
"""

import subprocess
import time
import json

def get_recent_candles(limit=20):
    """Get recent candles from database"""
    cmd = [
        'npx', 'wrangler', 'd1', 'execute', 'webapp-production',
        '--remote', '--command',
        f'SELECT id, timestamp, open, high, low, close FROM gold10_candles ORDER BY timestamp DESC LIMIT {limit}'
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd='/home/user/webapp')
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return []
    
    # Parse JSON
    start_idx = result.stdout.find('[')
    if start_idx == -1:
        return []
    
    data = json.loads(result.stdout[start_idx:])
    return data[0]['results']

def find_bad_candles(candles):
    """Find candles with wicks"""
    bad_ids = []
    for c in candles:
        o, h, l, cl = c['open'], c['high'], c['low'], c['close']
        expected_high = max(o, cl)
        expected_low = min(o, cl)
        
        if abs(h - expected_high) > 0.01 or abs(l - expected_low) > 0.01:
            bad_ids.append((c['id'], c['timestamp']))
            print(f"❌ Found bad candle: id={c['id']}, ts={c['timestamp']}, has WICK")
    
    return bad_ids

def delete_candles(ids):
    """Delete candles by IDs"""
    if not ids:
        return
    
    id_list = ','.join([str(i) for i, _ in ids])
    cmd = [
        'npx', 'wrangler', 'd1', 'execute', 'webapp-production',
        '--remote', '--command',
        f'DELETE FROM gold10_candles WHERE id IN ({id_list})'
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, cwd='/home/user/webapp')
    
    if result.returncode == 0:
        print(f"✅ Deleted {len(ids)} bad candles")
    else:
        print(f"Error deleting: {result.stderr}")

def main():
    print("=" * 80)
    print("Monitoring for bad candles (Ctrl+C to stop)...")
    print("=" * 80)
    
    iteration = 0
    while True:
        iteration += 1
        print(f"\n[{iteration}] Checking at {time.strftime('%H:%M:%S')}...")
        
        candles = get_recent_candles(20)
        if not candles:
            print("No candles found or error occurred")
            time.sleep(10)
            continue
        
        bad_candles = find_bad_candles(candles)
        
        if bad_candles:
            delete_candles(bad_candles)
        else:
            print(f"✅ All {len(candles)} candles are OK")
        
        # Wait 10 seconds before next check
        time.sleep(10)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nStopped monitoring.")
